### ISSUE TITLE
Not an issue - question on enhancing the edit view

### ISSUE THREAD

**Issue by johndpope** [GreenLimeSia/GenEdi#3]
so I'm using stylegan-web which is using vue.js to build out the site. It's a  simple frontend framework that makes components from javascript. https://github.com/johndpope/stylegan-web

![Screenshot_2020-12-29_00-04-16](https://user-images.githubusercontent.com/289994/103311545-c2345680-4a6e-11eb-80de-9f1e191a883c.png)

![Screenshot_2020-12-27_08-12-00](https://user-images.githubusercontent.com/289994/103311351-3fab9700-4a6e-11eb-93e9-90c3378db305.png)

The matplotlib controls are a tiny bit cooky / hard to get fine control.
I wonder if there would be interest to extend the latent vectors into this repo. I'll link these tickets up.

**Comment by johndpope** [comment]
I've updated the code - in my branch. http://www.github.com/johndpope/stylegan-web

I wondered in your code
feature_name_celeba_rename

is it possible to save out the feature_name_celeba_rename to individual pickles that can be reloaded?
eg. age.py
https://github.com/johndpope/stylegan-web/tree/master/latent_directions

**Comment by GreenLimeSia** [comment]
I have not updated it recently due to other work. Thanks for your hard work.

**Comment by zhanghongyong123456** [comment]
> so I'm using stylegan-web which is using vue.js to build out the site. It's a simple frontend framework that makes components from javascript. https://github.com/johndpope/stylegan-web
> 
> ![Screenshot_2020-12-29_00-04-16](https://user-images.githubusercontent.com/289994/103311545-c2345680-4a6e-11eb-80de-9f1e191a883c.png)
> 
> ![Screenshot_2020-12-27_08-12-00](https://user-images.githubusercontent.com/289994/103311351-3fab9700-4a6e-11eb-93e9-90c3378db305.png)
> 
> The matplotlib controls are a tiny bit cooky / hard to get fine control.
> I wonder if there would be interest to extend the latent vectors into this repo. I'll link these tickets up.
  I want to know  which project about 2 pic 
![Screenshot_2020-12-27_08-12-00](https://user-images.githubusercontent.com/289994/103311351-3fab9700-4a6e-11eb-93e9-90c3378db305.png)

**Comment by GreenLimeSia** [comment]
Hi @zhanghongyong123456 ：
I am sorry and do not understand your question. Please feel free to contact me if you have any questions. Thanks very much.

**Comment by zhanghongyong123456** [comment]
> Hi @zhanghongyong123456 ：
> I am sorry and do not understand your question. Please feel free to contact me if you have any questions. Thanks very much.

I'm sorry that my English is not very good, which makes it difficult for you to understand my intention.

Which project does this picture belong to, could you please tell me
![0001](https://user-images.githubusercontent.com/48466610/119656540-658e6980-be5d-11eb-8195-458d12e12078.png)

**Comment by GreenLimeSia** [comment]
Hi, @zhanghongyong123456 . It is a project for generating and editing arbitrary facial images. The PyTorch implementation is in [here](https://www.kaggle.com/greenlime/genandedi/edit?rvi=1). You can do facial image editing with our feature axis. Our paper can be found in [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9146645). 

If it is useful for you, please cite our work. Thank you very much.

The follow is a preview of the kaggle application, which you can copy as your own then use it does facial image editing:

![image](https://user-images.githubusercontent.com/28706611/119657069-08df7e80-be5e-11eb-9dd7-6f69896b97ab.png)

**Comment by zhanghongyong123456** [comment]
> Hi, @zhanghongyong123456 . It is a project for generating and editing arbitrary facial images. The PyTorch implementation is in [here](https://www.kaggle.com/greenlime/genandedi/edit?rvi=1). You can do facial image editing with our feature axis. Our paper can be found in [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9146645).
> 
> If it is useful for you, please cite our work. Thank you very much.
> 
> The follow is a preview of the kaggle application, which you can copy as your own then use it does facial image editing:
> 
> ![image](https://user-images.githubusercontent.com/28706611/119657069-08df7e80-be5e-11eb-9dd7-6f69896b97ab.png)



> Hi, @zhanghongyong123456 . It is a project for generating and editing arbitrary facial images. The PyTorch implementation is in [here](https://www.kaggle.com/greenlime/genandedi/edit?rvi=1). You can do facial image editing with our feature axis. Our paper can be found in [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9146645).
> 
> If it is useful for you, please cite our work. Thank you very much.
> 
> The follow is a preview of the kaggle application, which you can copy as your own then use it does facial image editing:
> 
> ![image](https://user-images.githubusercontent.com/28706611/119657069-08df7e80-be5e-11eb-9dd7-6f69896b97ab.png)

Thank you very much for your prompt reply. I will study it

**Comment by zhanghongyong123456** [comment]
![003](https://user-images.githubusercontent.com/48466610/119779568-67a70580-befb-11eb-84ff-f8c5fb322c09.png)
Not much use of Kaggle. Is that my problem or your problem

**Comment by GreenLimeSia** [comment]
It may be your issue since I use it now.
