### ISSUE TITLE
when i start train,get error:munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by dayu1979** [GreenLimeSia/GenEdi#4]
i execute :
python run_training.py head512.yaml --gpu 0 --resume
this is yaml:
# Here is an example training config file for 512x512 images.
channels: [32, 64, 128, 256, 512, 512, 512, 512]
tensorboard_log_dir: 'runs/stylegan2_head512'
tensorboard_image_interval: 500
checkpoint_dir: 'checkpoints/stylegan2_head512'
checkpoint_interval: 5000
data_dir: ~/head512/new2/
gpu: [0]
then get Error:
munmap_chunk(): invalid pointer
已放弃 (核心已转储)

**Comment by GreenLimeSia** [comment]
I have used the pre-trained StyleGAN2 model to realize image editing. Please see the original project for training the model in [here](https://github.com/Tetratrio/stylegan2_pytorch). Thanks for your attention.
